import{Quiz} from './db/db.js';

const  createQuiz = async (req, res) => {
    try {
        const { 
            title,
            description,
            total_duration,
            passingScore,
            header,
            instructions,
            footer,
            watermark,
            sections,
            createdBy
        } = req.body;

        // Basic validation
        if (!title || !createdBy) {
            return res.status(400).json({ 
                message: 'Title and createdBy are required' 
            });
        }

        // Create new quiz
        const newQuiz = new Quiz({
            title,
            description,
            timeLimit: total_duration,
            passingScore: passingScore || 70,
            createdBy,
            metadata: {
                header: header || [],
                instructions: instructions || [],
                footer: footer || [],
                watermark: watermark || {}
            },
            sections: sections.map(section => ({
                name: section.name,
                timerEnabled: section.timerEnabled,
                marks: section.marks,
                negativeMarks: section.negativeMarks,
                questions: section.questions,
                isAutogenerated: section.isAutogenerated || false
            }))
        });

        // Save to database
        const savedQuiz = await newQuiz.save();
        
        res.status(201).json({
            message: 'Quiz created successfully',
            quiz: savedQuiz
        });

    } catch (error) {
        console.error('Error creating quiz:', error);
        res.status(500).json({ 
            message: 'Failed to create quiz',
            error: error.message 
        });
    }
};


// Change the export at the bottom to:
export default {
  createQuiz,
  // Add other controller methods here as you implement them
};