import mongoose from 'mongoose';

const quizSchema = new mongoose.Schema({
    title: { type: String, required: true },
    description: { type: String },
    timeLimit: { type: Number }, // in minutes
    passingScore: { 
        type: Number,
        default: 70
    },
    createdBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
    },
    metadata: {
        header: { type: [String], default: [] },
        instructions: { type: [String], default: [] },
        footer: { type: [String], default: [] },
        watermark: { type: Object, default: {} }
    },
    sections: [{
        name: { type: String, required: true },
        timerEnabled: { type: Boolean, default: false },
        marks: { type: Number, default: 1 },
        negativeMarks: { type: Number, default: 0 },
        questions: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Question' }],
        isAutogenerated: { type: Boolean, default: false }
    }]
});

const Quiz = mongoose.model('Quiz', quizSchema);

export default Quiz;
